### ISSUE TITLE
setup node mailer

### ISSUE THREAD

**Issue by matthewjhough** [nathanmentley/michigan-for-revolution#3]
set up node mailer that sends out emails posted from form.

**Comment by nathanmentley** [comment]
server.js:~31

sets up a pluginUtils object.

That is passed into the plugin logic setup here:
https://api.m4r.skacahtoa.com/collections/entries/logic

It's read only to that sandboxed code.
But I think we'd want to setup a method in that pluginUtils object to send email.

That way when a form of type X is entered the admin can configure a script to send out an email.

The example plugin/logic code would be something like this:
`
let test = "Plugin logic for memberSignUp form saves";
let formData = data[1].data;

utils.log("start - " + test);

let message = "firstName: " + formData.firstName + "\n";
message += "lastName: " + formData.lastName + "\n";
utils.email.send("admin@example.com", "political group - new member signup", message);

utils.log("end - " + test);
`
